# Generated by Django 4.2.21 on 2025-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0013_district_lostanimal_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="district",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="district",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
    ]
